--PRODUCT-V1-2021-03-27
--DROP TABLE PRODUCT;
CREATE TABLE PRODUCT(
	ID VARCHAR2(100) PRIMARY KEY ,
	PNAME NVARCHAR2(60),
	PRICE NUMBER(17,3),
	PDESC NVARCHAR2(60)
);

CREATE OR REPLACE TRIGGER PRODUCT_ID_TRI --
BEFORE INSERT ON PRODUCT --
FOR EACH ROW --
BEGIN --
SELECT --
SYS_GUID() --
INTO :NEW.ID  --
FROM DUAL ;

END PRODUCT_ID_TRI --
;

INSERT INTO PRODUCT VALUES (null,'电视机',3200,'液晶曲面大电视');
INSERT INTO PRODUCT VALUES (null,'韭菜盒子',3,'味重请小心食用');
INSERT INTO PRODUCT VALUES (null,'益达',10,'韭菜伴侣');
INSERT INTO PRODUCT VALUES (null,'十三香',12,'守义牌');
